# Generated by Django 5.2.7 on 2026-01-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Designates whether this user has been approved by admin to access the system.', verbose_name='Is Approved'),
        ),
    ]
