# Generated by Django 5.2.7 on 2025-11-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_remove_bill_amount_bill_bill_total_bill_gst_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
