# Generated by Django 5.2.7 on 2025-11-29 06:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0004_alter_bill_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='override_bill_total',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bill',
            name='override_gst',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bill',
            name='override_gst_on_workportion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bill',
            name='override_lwc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bill',
            name='override_net_amount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bill',
            name='override_tds',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bill',
            name='gst_on_workportion_percentage',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='bill',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=18.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='bill',
            name='lwc_percentage',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='bill',
            name='tds_percentage',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
