# Generated by Django 5.2.7 on 2026-01-03 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0005_bill_override_bill_total_bill_override_gst_and_more'),
        ('gr', '0004_alter_gr_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='payment_done_from_gr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills_paid_from', to='gr.gr', verbose_name='Bill payment done from'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='Bill documents/%Y/%m/'),
        ),
    ]
