# Generated by Django 5.2.7 on 2026-01-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0006_add_payment_done_from_gr_and_update_document_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='Mark this record as demo data for testing', verbose_name='Is Demo'),
        ),
    ]
