# Generated by Django 5.2.7 on 2025-10-22 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('technical_sanction', '0001_initial'),
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_id', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField()),
                ('agency_name', models.CharField(max_length=300)),
                ('work_order', models.FileField(blank=True, null=True, upload_to='work_orders/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('technical_sanction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='technical_sanction.technicalsanction')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenders', to='works.work')),
            ],
            options={
                'verbose_name': 'Tender',
                'verbose_name_plural': 'Tenders',
            },
        ),
    ]
