# Generated by Django 5.2.7 on 2025-10-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='work_order',
            field=models.FileField(blank=True, null=True, upload_to='work_orders/%Y/%m/%d/'),
        ),
    ]
