# Generated by Django 5.2.7 on 2025-10-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0002_alter_tender_work_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='financial_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tender',
            name='financial_verification_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='loa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tender',
            name='loa_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='online_offline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tender',
            name='online_offline_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='technical_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tender',
            name='technical_verification_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
