# Generated by Django 5.2.7 on 2025-11-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0003_tender_financial_verification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
