# Generated by Django 5.2.7 on 2026-01-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0004_alter_tender_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='work_order',
            field=models.FileField(blank=True, null=True, upload_to='Tender work orders/%Y/%m/'),
        ),
    ]
