# Generated by Django 5.2.7 on 2026-01-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0005_alter_tender_work_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tender',
            name='online_offline',
        ),
        migrations.RemoveField(
            model_name='tender',
            name='online_offline_date',
        ),
        migrations.AddField(
            model_name='tender',
            name='awarded_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='emd_awarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tender',
            name='emd_supporting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tender',
            name='offline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tender',
            name='offline_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tender',
            name='online_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='supporting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='work_order_tick',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tender',
            name='work_order_tick_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
