# Generated by Django 5.2.7 on 2026-01-03 17:30

from django.db import migrations, models
import django.db.models.deletion


def assign_technical_sanctions_to_existing_tenders(apps, schema_editor):
    """Assign a technical sanction to any tenders that don't have one"""
    Tender = apps.get_model('tender', 'Tender')
    TechnicalSanction = apps.get_model('technical_sanction', 'TechnicalSanction')
    
    # Find tenders without technical_sanction
    tenders_without_ts = Tender.objects.filter(technical_sanction__isnull=True)
    
    if tenders_without_ts.exists():
        # For each tender, try to find a technical sanction for the same work
        for tender in tenders_without_ts:
            # Find the first technical sanction for this work
            ts = TechnicalSanction.objects.filter(work=tender.work).first()
            if ts:
                tender.technical_sanction = ts
                tender.save()
            else:
                # If no TS exists for this work, we need to delete the tender
                # or create a TS. For safety, we'll raise an error.
                raise ValueError(
                    f"Tender {tender.tender_id} (ID: {tender.id}) has no technical sanction "
                    f"and no technical sanctions exist for work {tender.work.id}. "
                    f"Please assign a technical sanction to this tender or delete it before running this migration."
                )


class Migration(migrations.Migration):

    dependencies = [
        ('technical_sanction', '0004_technicalsanction_sub_name'),
        ('tender', '0006_remove_tender_online_offline_and_more'),
    ]

    operations = [
        # First, assign technical sanctions to existing tenders
        migrations.RunPython(assign_technical_sanctions_to_existing_tenders, migrations.RunPython.noop),
        # Then, make the field required
        migrations.AlterField(
            model_name='tender',
            name='technical_sanction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenders', to='technical_sanction.technicalsanction'),
        ),
    ]

