# Generated by Django 5.2.7 on 2025-10-22 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalSanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_portion', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('royalty', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('testing', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('work_portion_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('gst', models.DecimalField(decimal_places=2, default=18.0, help_text='GST Percentage', max_digits=5)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('consultancy', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('contingency', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('labour_insurance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('final_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('noting', models.BooleanField(default=False)),
                ('order', models.BooleanField(default=False)),
                ('online_offline', models.BooleanField(default=False)),
                ('online_offline_date', models.DateField(blank=True, null=True)),
                ('technical_verification', models.BooleanField(default=False)),
                ('technical_verification_date', models.DateField(blank=True, null=True)),
                ('financial_verification', models.BooleanField(default=False)),
                ('financial_verification_date', models.DateField(blank=True, null=True)),
                ('loa', models.BooleanField(default=False)),
                ('loa_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_sanctions', to='works.work')),
            ],
            options={
                'verbose_name': 'Technical Sanction',
                'verbose_name_plural': 'Technical Sanctions',
            },
        ),
    ]
