# Generated by Django 5.2.7 on 2025-10-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical_sanction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicalsanction',
            name='financial_verification',
        ),
        migrations.RemoveField(
            model_name='technicalsanction',
            name='financial_verification_date',
        ),
        migrations.RemoveField(
            model_name='technicalsanction',
            name='loa',
        ),
        migrations.RemoveField(
            model_name='technicalsanction',
            name='loa_date',
        ),
        migrations.RemoveField(
            model_name='technicalsanction',
            name='online_offline',
        ),
        migrations.RemoveField(
            model_name='technicalsanction',
            name='online_offline_date',
        ),
        migrations.RemoveField(
            model_name='technicalsanction',
            name='technical_verification',
        ),
        migrations.RemoveField(
            model_name='technicalsanction',
            name='technical_verification_date',
        ),
        migrations.AddField(
            model_name='technicalsanction',
            name='contingency_percentage',
            field=models.DecimalField(decimal_places=2, default=4.0, max_digits=5, verbose_name='Contingency %'),
        ),
        migrations.AddField(
            model_name='technicalsanction',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=18.0, max_digits=5, verbose_name='GST %'),
        ),
        migrations.AddField(
            model_name='technicalsanction',
            name='labour_insurance_percentage',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Labour Insurance %'),
        ),
        migrations.AddField(
            model_name='technicalsanction',
            name='noting_date',
            field=models.DateField(blank=True, null=True, verbose_name='Noting Date'),
        ),
        migrations.AddField(
            model_name='technicalsanction',
            name='order_date',
            field=models.DateField(blank=True, null=True, verbose_name='Order Date'),
        ),
        migrations.AlterField(
            model_name='technicalsanction',
            name='consultancy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Consultancy'),
        ),
        migrations.AlterField(
            model_name='technicalsanction',
            name='contingency',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='Contingency Amount'),
        ),
        migrations.AlterField(
            model_name='technicalsanction',
            name='final_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='Final Total'),
        ),
        migrations.AlterField(
            model_name='technicalsanction',
            name='grand_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='Grand Total'),
        ),
        migrations.AlterField(
            model_name='technicalsanction',
            name='gst',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='GST Amount'),
        ),
        migrations.AlterField(
            model_name='technicalsanction',
            name='labour_insurance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='Labour Insurance Amount'),
        ),
        migrations.AlterField(
            model_name='technicalsanction',
            name='noting',
            field=models.BooleanField(default=False, verbose_name='Noting'),
        ),
        migrations.AlterField(
            model_name='technicalsanction',
            name='order',
            field=models.BooleanField(default=False, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='technicalsanction',
            name='work_portion_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='Work Portion Total'),
        ),
    ]
