# Generated by Django 5.2.7 on 2025-11-29 06:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical_sanction', '0002_remove_technicalsanction_financial_verification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalsanction',
            name='override_contingency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='technicalsanction',
            name='override_final_total',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='technicalsanction',
            name='override_grand_total',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='technicalsanction',
            name='override_gst',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='technicalsanction',
            name='override_labour_insurance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='technicalsanction',
            name='override_work_portion_total',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='technicalsanction',
            name='contingency_percentage',
            field=models.DecimalField(decimal_places=2, default=4.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Contingency %'),
        ),
        migrations.AlterField(
            model_name='technicalsanction',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=18.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='GST %'),
        ),
        migrations.AlterField(
            model_name='technicalsanction',
            name='labour_insurance_percentage',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Labour Insurance %'),
        ),
    ]
