# Generated by Django 5.2.7 on 2025-12-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical_sanction', '0003_technicalsanction_override_contingency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalsanction',
            name='sub_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub Name'),
        ),
    ]
