# Generated by Django 5.2.7 on 2026-01-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical_sanction', '0004_technicalsanction_sub_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalsanction',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='Mark this record as demo data for testing', verbose_name='Is Demo'),
        ),
    ]
