# Generated by Django 5.2.7 on 2025-10-22 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name_of_work', models.CharField(max_length=500)),
                ('aa', models.DecimalField(decimal_places=2, help_text='Administrative Approval', max_digits=15)),
                ('ra', models.DecimalField(decimal_places=2, default=0, help_text='Revised Approval', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='gr.gr')),
            ],
            options={
                'verbose_name': 'Work',
                'verbose_name_plural': 'Works',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Spill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ara', models.DecimalField(decimal_places=2, help_text='Additional Revised Approval', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spills', to='works.work')),
            ],
            options={
                'verbose_name': 'Spill (ARA)',
                'verbose_name_plural': 'Spills (ARA)',
            },
        ),
    ]
