# Generated by Django 5.2.7 on 2026-01-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_alter_work_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='spill',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='Mark this record as demo data for testing', verbose_name='Is Demo'),
        ),
        migrations.AddField(
            model_name='work',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='Mark this record as demo data for testing', verbose_name='Is Demo'),
        ),
    ]
