# Generated by Django 5.2.7 on 2026-01-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_spill_is_demo_work_is_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='cancel_details',
            field=models.TextField(blank=True, help_text='Additional details about cancellation (e.g., new work name, new department name, or any explanation)', null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='cancel_reason',
            field=models.CharField(blank=True, choices=[('SHIFTED_TO_OTHER_WORK', 'Work shifted to another work'), ('MOVED_TO_OTHER_DEPARTMENT', 'Work assigned to different department')], help_text='Reason for cancellation', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='is_cancelled',
            field=models.BooleanField(default=False, help_text='Mark this work as cancelled', verbose_name='Is Cancelled'),
        ),
    ]
