# Generated by Django 5.2.7 on 2025-10-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gr',
            name='document',
            field=models.FileField(blank=True, help_text='Upload the Government Resolution document (PDF, Word, or image)', null=True, upload_to='gr_documents/%Y/%m/%d/', verbose_name='GR Document'),
        ),
        migrations.AlterField(
            model_name='gr',
            name='date',
            field=models.DateField(verbose_name='GR Date'),
        ),
        migrations.AlterField(
            model_name='gr',
            name='gr_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='GR Number'),
        ),
    ]
