# Generated by Django 5.2.7 on 2025-11-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gr', '0002_gr_document_alter_gr_date_alter_gr_gr_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gr',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='GR Date'),
        ),
    ]
