# Generated by Django 5.2.7 on 2025-12-30 15:52

import apps.gr.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gr', '0003_alter_gr_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gr',
            name='document',
            field=models.FileField(blank=True, help_text='Upload the Government Resolution document (PDF, Word, or image)', null=True, upload_to=apps.gr.models.gr_document_upload_path, verbose_name='GR Document'),
        ),
    ]
